# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-02 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_public_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='public_time',
            field=models.DateTimeField(null=True),
        ),
    ]
