# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-02 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180102_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='public_time',
            new_name='publish_time',
        ),
    ]
